[package]
name = "funkus_dialogue_core"
version = "0.1.0"
edition = "2024"
description = "Core functionality for the Bevy dialogue system"
license = "Apache-2.0"
repository = "https://github.com/StudioFunkus/funkus_dialogue"
homepage = "https://github.com/StudioFunkus/funkus_dialogue"

[dependencies]
bevy = { version = "0.18", default-features = false, features = ["default_app"] }
tracing = "0.1"
funkus_dialogue_derive = { path = "../funkus_dialogue_derive" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = { version = "2", default-features = false }
bevy_common_assets = { version = "0.15", features = ["json", "ron"] }
petgraph = "0.7"
bevy_egui = { version = "0.39", optional = true }
inventory = "0.3"

[dev-dependencies]
bevy = "0.18"

[features]
default = []
debug_ui = ["bevy_egui"]
